/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TourMaker;

import TourMaker.gui.MainScreen;
import TourMaker.util.LAFUtil;

public class App {

  public static void main(String[] args) {
    LAFUtil.initialize();
    
    MainScreen.getInstance();
  }
}
